version: '3.8'

volumes:
  db-data:

services:
  db:
    image: library/postgres:12.4-alpine
    environment:
      POSTGRES_DB: restapi
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      LANG: pt_BR.utf8
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data